language: bash
sudo: required
services:
  - docker
install: true

env:
  - GROUP=weaveworksdemos COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=orders.net;

script:
  - set -e
  - ./scripts/build.sh;

after_success:
  - set -e;
  - if [ -z "$DOCKER_PASS" ] ; then
      echo "This is a build triggered by an external PR. Skipping docker push.";
      exit 0;
    fi;
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS;
  - ./scripts/push.sh

before_install:
- openssl aes-256-cbc -K $encrypted_3f03c979859d_key -iv $encrypted_3f03c979859d_iv
  -in ${REPO}_deploy_rsa.enc -out orders_deploy_rsa -d
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/${REPO}_deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/${REPO}_deploy_rsa

addons:
  ssh_known_hosts: $BASTION
deploy:
  provider: script
  skip_cleanup: true
  # The deploy.sh file actually points to the deploy file on the bastion. Not one in the repo.
  script: ssh -o StrictHostKeyChecking=no $BASTION_USER@$BASTION ./deploy.sh ${REPO} $COMMIT
  on:
    branch: master
